### ISSUE TITLE
Way to run tasks

### ISSUE THREAD

**Issue by hirokiky** [docker-library/celery#1]
Hi, I don't know how to run tasks by using this Dockerfile.
- Where should I place `tasks.py` file to register tasks to run?
- How can I notice new tasks for this container?

If you know, please tell me.  :smiley:

**Comment by kjr** [comment]
You can mount your tasks.py into the container in the users home directory (`/home/user`) and I think use the `CELERY_APP` environment variable (this worked for me, but I was browsing the issues here hoping to find a list of available environment variables...)

```
docker run --volume /path/to/tasks.py:/home/user/tasks.py --env CELERY_APP=tasks celery
```

Not sure how you would notice new tasks.. any change to the file on the host would be seen by the container, but I don't think it will reload. Still, it's quick to restart the container...

**Comment by AdrianRibao** [comment]
This needs to be documented.

How can this be used with django for example?

**Comment by tianon** [comment]
+1 for some documentation :innocent: (what we've got is impossibly sparse right now: https://github.com/docker-library/docs/blob/master/celery/content.md)

**Comment by esseti** [comment]
that's tricky. i tried with docker-compose but i can't find a way. has anyone been able to run the celery in docker and use the integration with django??

**Comment by bittner** [comment]
Using this image seems ridiculous. If you have an application container, as you usually have with Django, you need all dependencies (things you import in `tasks.py`) installed in this container again.

That's why other projects (e.g. cookiecutter-django) [reuse the application container](https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/docker-compose.yml#L62-L71) for Celery, and only run a different command (`command: celery ... worker`) against it with docker-compose.

**Comment by tianon** [comment]
Indeed, Sentry includes a way to run Celery directly as well.

Pondering whether this image actually makes sense to simply deprecate,
similar to the deprecation of the django image (and for similar reasons).

**Comment by tianon** [comment]
I've opened https://github.com/docker-library/celery/issues/12 to discuss this image's deprecation.  In the meantime, I'm going to close this issue since I think the original question is as solved as it's going to get. :+1:

**Comment by ArnaudPel** [comment]
Agreed, it's not going to be much more difficult to replace this image with a build on a standard Python image with celery added to pip's `requirements.txt` for example.

Actually, doing so in the first place would have saved me two hours yesterday: This celery docker image ignores the broker url when provided from inside python like so `app = Celery('tasks', broker='my url')`, and only allows it to be set from the docker env variable `CELERY_BROKER_URL`. Ok this is kinda hinted in the doc, my bad for not reading carefully. But it's clearly counter-intuitive and time consuming to find this out when having your nose in the code and not expecting some of the parameters to be forced but not the others (the `backend` argument is not forced like this for example, although it has the same kind of properties that could refer to other docker containers: host, port, ...).

Anyway I'm rambling again, I came here to comment about this parameters forcing but since the whole thing is deprecated I reckon there's no need.
